### ISSUE TITLE
audio?

### ISSUE THREAD

**Issue by eijowk** [dc35956/gk7102-hack#1]
Is it possible to enable the mic to get audio in the rtsp stream?
Is there a setting somewhere or is it something that is missing in the code?
I have some Guudgo SC02 cameras. 
Thx!

**Comment by 3gyptian** [comment]
I have the same question as well.  Everything else works great. Have a Y4A-ZA2 
thanks!

**Comment by laserlance** [comment]
For audio, append /0/av0 or /0/av1 to the RTSP URL. The former sends high resolution video, the latter sends low.

**Comment by shahmirthesquid** [comment]
> For audio, append /0/av0 or /0/av1 to the RTSP URL. The former sends high resolution video, the latter sends low.

THANK YOU.... seriously thank you so much.... I was stuck on this audio issue for many days now trying to understand why my camera would have audio in the app but not in BlueIris. This fixed my issue completely. God bless you my friend.
