### ISSUE TITLE
Disable whitelight

### ISSUE THREAD

**Issue by RussH007** [dc35956/gk7102-hack#13]
Thanks for the hack. Works great and nice to be able to use WiFi without cloud access. I have an issue where when it's dark and I move past the camera, then the whitelight comes on for a minute or so. Any idea how to stop it doing that? I can manually turn the whitelight off using gio - s 15 0  but next time I walk past the camera the whitelight comes on again. Any idea how I can permanently disable the white lights and just leave IR leds on at night?. Thx. P. S. Noticed that config.cfg changed a few days ago {before I installed the hack} 
and it wasn't changed by me

**Comment by RussH007** [comment]
hwcfg.ini  - support_doublelight = 1 (was 2)

**Comment by dc35956** [comment]
I will add this information to the README if someone else want to know how to disable the whitelight.
