### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by RobertByrnes** [dc35956/gk7102-hack#7]
Hi, regarding the config file. Please can you confirm whether to set HACK-WIFI to YES or NO. Have model CICP-GC13H with GK7102S and have not succeeded yet.  Any help with configuring the hack would be gratefully received. Cheers...

**Comment by dc35956** [comment]
There was a bug with the HACK-WIFI setting. [This commit ](https://github.com/dc35956/gk7102-hack/commit/b488aa2fa1ca157a9031d91d12f7f47308840800)should have fixed it.

Update your files and try if it fixes the problem on your side.
